name: Build Brave

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: |
        mkdir -p $PWD/out
        sudo chown -R 1000:1000 $PWD/out
        bash cmd.sh
