name: Build Brave

on:
  workflow_dispatch:


jobs:

  build-1:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: |
        mkdir -p $PWD/out
        sudo chown -R 1000:1000 $PWD/out
        timeout 2m bash cmd.sh || echo

    - name: Save build result
      run: |
        sudo tar cvf build-1.tar out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-1
        path: build-1.tar
        compression-level: 0

  build-2:
    runs-on: ubuntu-latest
    needs: build-1
    steps:
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-1
    - run: |
        sudo tar xvf build-1.tar
        sudo rm build-1.tar
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        mkdir -p $PWD/out
        sudo chown -R 1000:1000 $PWD/out
        timeout 10m bash cmd.sh || echo
