name: Build Brave

on:
  workflow_dispatch:


jobs:

  build-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Setup version
      id: version
      run: |
        echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
        echo "The brave version is $VERSION"

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  if : ${{ github.event_name == 'workflow_dispatch' }}

    - name: Download the Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/brave-browser:$VERSION

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo fallocate -l 32G /mnt/swapfile
        sudo chmod 600 /swapfile
        sudo chmod 600 /mnt/swapfile
        sudo mkswap /swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /swapfile
        sudo swapon /mnt/swapfile


    
    - name: Run build
      run: |
        sudo mkdir -p /mnt/build
        sudo mkdir -p /mnt/build/out
        sudo chown `whoami` /mnt/build
        sudo chown -R 1000:1000 /mnt/build/out
        timeout 315m bash cmd.sh || echo
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-1
        path: /mnt/build/out.tar
        compression-level: 0


  build-2:
    runs-on: ubuntu-latest
    needs: build-1
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
      
    - name: Mkdir /out/build
      run: |
        sudo mkdir -p /mnt/build
        sudo chown `whoami` /mnt/build
    - name: Download build cache
      uses: actions/download-artifact@v4
      with:
        name: build-1
        path: /mnt/build

    - name: Restore build result
      run: |
        sudo tar -xvf /mnt/build/out.tar -C /
        sudo rm /mnt/build/out.tar
      
    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
    
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-2
        path: /mnt/build/out.tar
        compression-level: 0



  build-3:
    runs-on: ubuntu-latest
    needs: build-2
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
      
    - name: Mkdir /out/build
      run: |
        sudo mkdir -p /mnt/build
        sudo chown `whoami` /mnt/build
    - name: Download build cache
      uses: actions/download-artifact@v4
      with:
        name: build-2
        path: /mnt/build

    - name: Restore build result
      run: |
        sudo tar -xvf /mnt/build/out.tar -C /
        sudo rm /mnt/build/out.tar
      
    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
    
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-3
        path: /mnt/build/out.tar
        compression-level: 0


  build-4:
    runs-on: ubuntu-latest
    needs: build-3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
      
    - name: Mkdir /out/build
      run: |
        sudo mkdir -p /mnt/build
        sudo chown `whoami` /mnt/build
    - name: Download build cache
      uses: actions/download-artifact@v4
      with:
        name: build-3
        path: /mnt/build

    - name: Restore build result
      run: |
        sudo tar -xvf /mnt/build/out.tar -C /
        sudo rm /mnt/build/out.tar
      
    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
    
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-4
        path: /mnt/build/out.tar
        compression-level: 0


  build-5:
    runs-on: ubuntu-latest
    needs: build-4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
      
    - name: Mkdir /out/build
      run: |
        sudo mkdir -p /mnt/build
        sudo chown `whoami` /mnt/build
    - name: Download build cache
      uses: actions/download-artifact@v4
      with:
        name: build-4
        path: /mnt/build

    - name: Restore build result
      run: |
        sudo tar -xvf /mnt/build/out.tar -C /
        sudo rm /mnt/build/out.tar
      
    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
    
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-5
        path: /mnt/build/out.tar
        compression-level: 0


  build-6:
    runs-on: ubuntu-latest
    needs: build-5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
      
    - name: Mkdir /out/build
      run: |
        sudo mkdir -p /mnt/build
        sudo chown `whoami` /mnt/build
    - name: Download build cache
      uses: actions/download-artifact@v4
      with:
        name: build-5
        path: /mnt/build

    - name: Restore build result
      run: |
        sudo tar -xvf /mnt/build/out.tar -C /
        sudo rm /mnt/build/out.tar
      
    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Create swap file
      run: |
        sudo fallocate -l 32G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
    
    - name: tar out
      run: |
        sudo rm -rf /mnt/build/out/Static/chrome.tmp*
        sudo rm -rf /mnt/build/out/Static/thinlto-cache
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-6
        path: /mnt/build/out.tar
        compression-level: 0