name: Build Brave

on:
  workflow_dispatch:


jobs:

  build-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Download the Docker image
      run: docker pull chezzn/brave
      
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  if : ${{ github.event_name == 'workflow_dispatch' }}
    
    - name: Run build
      run: |
        mkdir -p $PWD/out
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-1
        path: out

  build-2:
    runs-on: ubuntu-latest
    needs: build-1
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
        
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-1

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-2
        path: out
  build-3:
    runs-on: ubuntu-latest
    needs: build-2
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
        
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-2

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-3
        path: out

  build-4:
    runs-on: ubuntu-latest
    needs: build-3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
        
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-3

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-4
        path: out


  build-5:
    runs-on: ubuntu-latest
    needs: build-4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
        
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-4

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-5
        path: out

  build-6:
    runs-on: ubuntu-latest
    needs: build-5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"
        
    - name: Download build1 cache
      uses: actions/download-artifact@v4
      with:
        name: build-5

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Run build
      run: | 
        sudo chown -R 1000:1000 $PWD/out
        timeout 5h bash cmd.sh || echo
        sudo chown -R `whoami` $PWD/out
        
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: build-6
        path: out
