name: Debug workflow

on:
  workflow_dispatch:

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "docker_buildkit"

    - name: Download the Docker image
      run: docker pull chezzn/brave

    - name: Prepare Environment
      run: |
        sudo mkdir -p /mnt/build
        sudo mkdir -p /mnt/build/out
        sudo chown `whoami` /mnt/build
        sudo chown -R 1000:1000 /mnt/build/out

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if : ${{ github.event_name == 'workflow_dispatch' }}
      
    - name: Run build
      run: | 
        timeout 315m bash cmd.sh || echo
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if : ${{ github.event_name == 'workflow_dispatch' }}
      
    - name: tar out
      run: |
        sudo tar --use-compress-program="zstd -1 -T0" -cvpf /mnt/build/out.tar /mnt/build/out
        
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-1
        path: /mnt/build/out.tar
        compression-level: 0
