name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag brave:v1.69.162
