name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "container_tools"

    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Log into registry
    #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: podman build . --file Dockerfile --tag brave # ghcr.io/${{ github.repository_owner }}/brave:v1.69.162
    - name: Save container image
      run: |
         podman save brave > brave.tar
      
    - name: Upload container image
      uses: actions/upload-artifact@v4
      with:
        name: brave
        path: brave.tar
        retention-days: 1
        compression-level: 0    
            
    #- name: Push image
    #  run: |
    #    docker push ghcr.io/${{ github.repository_owner }}/brave:v1.69.162
